knpu_oauth2_client:
    clients:
        line:
            type: generic
            provider_class: App\Adapter\Line\LineClient
            client_id: '%env(LINE_CHANNEL_ID)%'
            client_secret: '%env(LINE_CHANNEL_SECRET)%'
            redirect_route: line_callback
            redirect_params: {}
