security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        line_auth:
            pattern: ^/line/auth
            anonymous: true
        main:
            guard:
                authenticators:
                    - App\Adapter\Line\LineAuthenticator
            logout:
                path:   logout

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
